CREATE TABLE TIPO_INFORMACION (
    CODIGO_TIPO_INFORMACION int NOT NULL PRIMARY KEY,
    NOMBRE_TIPO_INFORMACION varchar(255)
);

CREATE TABLE TIPO_MENSAJE (
    CODIGO_TIPO int NOT NULL PRIMARY KEY,
    NOMBRE_TIPO varchar(255)
);

CREATE TABLE PROYECTO (
    CODIGO_PROYECTO int NOT NULL PRIMARY KEY,
    NOMBRE_PROYECTO varchar(255)
);

CREATE TABLE PRODUCTO (
    CODIGO_PRODUCTO int NOT NULL PRIMARY KEY,
    DESCRIPCION_PRODUCTO nvarchar(511)
);




CREATE TABLE FORMATO_MENSAJE (
    CODIGO_FORMATO_MENSAJE int NOT NULL PRIMARY KEY,
    CODIGO_TIPO int NOT NULL,  
	CODIGO_TIPO_INFORMACION int NOT NULL,
    NOMBRE nvarchar(255),
    REMITENTE nvarchar(255),
    ASUNTO nvarchar(MAX)
	 FOREIGN KEY (CODIGO_TIPO) REFERENCES TIPO(CODIGO_TIPO),
	 FOREIGN KEY (CODIGO_TIPO_INFORMACION) REFERENCES TIPO_INFORMACION(CODIGO_TIPO_INFORMACION)
);


CREATE TABLE PRODUCTO_PROYECTO (
    CODIGO_PROYECTO int NOT NULL ,
    CODIGO_PRODUCTO int NOT NULL ,  
	 FOREIGN KEY (CODIGO_PROYECTO) REFERENCES PROYECTO(CODIGO_PROYECTO),
	 FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
);

CREATE TABLE MENSAJE (
    CODIGO_MENSAJE int NOT NULL PRIMARY KEY,
    CODIGO_PROYECTO int NOT NULL,
    CODIGO_PRODUCTO int NOT NULL ,  
    CODIGO_FORMATO_MENSAJE int NOT NULL, 
	FOREIGN KEY (CODIGO_PROYECTO) REFERENCES PROYECTO(CODIGO_PROYECTO),
	FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO),
	FOREIGN KEY (CODIGO_FORMATO_MENSAJE) REFERENCES FORMATO_MENSAJE(CODIGO_FORMATO_MENSAJE),
);


USE [PRUEBA_PROAMERICA]
GO

USE [PRUEBA_PROAMERICA]
GO

INSERT INTO [dbo].[PRODUCTO]
           ([CODIGO_PRODUCTO]
           ,[DESCRIPCION_PRODUCTO])
     VALUES
           (3
           ,'Premia Platinum')
GO

USE [PRUEBA_PROAMERICA]
GO


USE [PRUEBA_PROAMERICA]
GO

INSERT INTO [PRUEBA_PROAMERICA].[dbo].[TIPO]
           ([CODIGO_TIPO]
           ,[NOMBRE_TIPO])
     VALUES
           (3
           ,'mensaje en el estado ')
GO
USE [PRUEBA_PROAMERICA]
GO

INSERT INTO [PRUEBA_PROAMERICA].[dbo].[TIPO_INFORMACION]
           ([CODIGO_TIPO_INFORMACION]
           ,[NOMBRE_TIPO_INFORMACION])
     VALUES
           (3
           ,'mensaje de promoción')
GO

/*
A.	Escriba la consulta en SQL que devuelva el nombre del proyecto y sus productos correspondientes del proyecto premia cuyo código es 1
*/

SELECT  PRO.NOMBRE_PROYECTO,PRD.CODIGO_PRODUCTO,PRD.DESCRIPCION_PRODUCTO FROM [PRUEBA_PROAMERICA].[dbo].[PROYECTO] AS PRO
INNER JOIN [PRUEBA_PROAMERICA].[dbo].PRODUCTO_PROYECTO AS PRPY ON (PRO.CODIGO_PROYECTO = PRPY.CODIGO_PRODUCTO)
INNER JOIN [PRUEBA_PROAMERICA].[dbo].PRODUCTO AS PRD ON (PRPY.CODIGO_PRODUCTO = PRD.CODIGO_PRODUCTO)
WHERE PRO.NOMBRE_PROYECTO = 'PREMIA' AND PRO.CODIGO_PROYECTO = 1

/*
B.	Escriba una consulta SQL que devuelva los distintos mensajes que hay, indicando a qué proyecto y producto pertenecen.
*/

SELECT  
    MSJ.CODIGO_PROYECTO,
	MSJ.CODIGO_PRODUCTO,
    FMSJ.NOMBRE,
    FMSJ.REMITENTE,
    FMSJ.ASUNTO
	FROM [PRUEBA_PROAMERICA].[dbo].[FORMATO_MENSAJE] AS  FMSJ  INNER JOIN[PRUEBA_PROAMERICA].[dbo].[MENSAJE] AS MSJ
	ON (FMSJ.CODIGO_FORMATO_MENSAJE   =  MSJ.CODIGO_FORMATO_MENSAJE)


/*
C.	Escriba una consulta SQL que devuelva los distintos mensajes que hay, indicando a qué proyecto y producto pertenecen.
Pero si el mensaje está en todos los productos de un proyecto, en lugar de mostrar cada producto,
debe mostrar el nombre del proyecto y un solo producto que diga “TODOS”.
*/

SELECT  
    MSJ.CODIGO_PROYECTO,
	MSJ.CODIGO_PRODUCTO,
	'TODOS',
    FMSJ.NOMBRE,
    FMSJ.REMITENTE,
    FMSJ.ASUNTO,
	COUNT(MSJ.CODIGO_PRODUCTO) 
	FROM [PRUEBA_PROAMERICA].[dbo].[FORMATO_MENSAJE] AS  FMSJ  INNER JOIN [PRUEBA_PROAMERICA].[dbo].[MENSAJE] AS MSJ
	ON (FMSJ.CODIGO_FORMATO_MENSAJE   =  MSJ.CODIGO_FORMATO_MENSAJE) INNER JOIN  [PRUEBA_PROAMERICA].[dbo].[PRODUCTO] AS PRO
	ON (MSJ.CODIGO_PRODUCTO = PRO.CODIGO_PRODUCTO) GROUP BY 
	MSJ.CODIGO_PROYECTO,
	MSJ.CODIGO_PRODUCTO,
    FMSJ.NOMBRE,
    FMSJ.REMITENTE,
    FMSJ.ASUNTO
	HAVING COUNT(MSJ.CODIGO_PRODUCTO)  = (SELECT COUNT(*) FROM [PRUEBA_PROAMERICA].[dbo].[PRODUCTO])
	UNION 
SELECT  
    MSJ.CODIGO_PROYECTO,
	MSJ.CODIGO_PRODUCTO,
	PRO.DESCRIPCION_PRODUCTO,
    FMSJ.NOMBRE,
    FMSJ.REMITENTE,
    FMSJ.ASUNTO,
	COUNT(MSJ.CODIGO_PRODUCTO) 
	FROM [PRUEBA_PROAMERICA].[dbo].[FORMATO_MENSAJE] AS  FMSJ  INNER JOIN [PRUEBA_PROAMERICA].[dbo].[MENSAJE] AS MSJ
	ON (FMSJ.CODIGO_FORMATO_MENSAJE   =  MSJ.CODIGO_FORMATO_MENSAJE) INNER JOIN  [PRUEBA_PROAMERICA].[dbo].[PRODUCTO] AS PRO
	ON (MSJ.CODIGO_PRODUCTO != PRO.CODIGO_PRODUCTO) 
	GROUP BY 
	MSJ.CODIGO_PROYECTO,
	MSJ.CODIGO_PRODUCTO,
	PRO.DESCRIPCION_PRODUCTO,
    FMSJ.NOMBRE,
    FMSJ.REMITENTE,
    FMSJ.ASUNTO
	HAVING COUNT(MSJ.CODIGO_PRODUCTO)  < (SELECT COUNT(*) FROM [PRUEBA_PROAMERICA].[dbo].[PRODUCTO])